name: Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
        id: size
      - uses: ./.github/actions/action-remove-labels
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            ${{ steps.size.outputs.stale_labels }}
      - uses: ./.github/actions/action-add-labels
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            ${{ steps.size.outputs.new_label }}
